//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budgeting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public int CategoryId { get; set; }
        public decimal Amount { get; set; }
        public bool Expenditure { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public System.DateTime DateOfActivity { get; set; }
        public Nullable<int> RecurringDay { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Pretax { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
