//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budgeting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BudgetPlan()
        {
            this.BudgetPlanCategories = new HashSet<BudgetPlanCategory>();
        }
    
        public int BudgetPlanId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetPlanCategory> BudgetPlanCategories { get; set; }
    }
}
