//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budgeting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetPlanCategory
    {
        public int BudgetPlanCategoryId { get; set; }
        public int BudgetPlanId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<decimal> AllocatedAmount { get; set; }
        public Nullable<decimal> AllocatedPercentage { get; set; }
        public bool UsePercent { get; set; }
    
        public virtual BudgetPlan BudgetPlan { get; set; }
        public virtual Category Category { get; set; }
    }
}
